name: CI for eAI-Repair-Toolkit

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  pre:
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: "same_content_newer"
        skip_after_successful_duplicate: true

  lint:
    needs: pre
    if: needs.pre.outputs.should_skip != 'true'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        : # fix to 0.4.0 to avoid UP031
        pip install "ruff==0.4.0"
    - name: Lint with ruff
      run: ruff check --output-format=github .

  testing:
    needs: pre
    if: needs.pre.outputs.should_skip != 'true'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Cache venv
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[test]

    - name: Cache keras resources
      id: restore-keras-cache
      uses: actions/cache@v4
      with:
        path: ~/.keras
        key: keras-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('tests/repair/conftest.py') }}

    - name: Run tests
      run: pytest --cov-report=xml --cov=repair -n=auto tests/

    - name: Report coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true
