name: CI for eAI-repair

on: [push, pull_request]

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: 'same_content_newer'

  lint:
    needs: pre
    if: needs.pre.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Lint with ruff
      run: |
        ruff check --format=github .
    - name: Check format with black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "."

  testing:
    needs: pre
    if: needs.pre.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Cache venv
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
        cache-dependency-path: |
          **/pyproject.toml
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[test]
    - name: Run tests
      run: pytest --cov-report=xml --cov=repair tests/
    - name: Report coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true
