name: "Semantic PR"

on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            refactor
            chore
            tests
            build
            ci
            revert
          scopes: |
            bdd_image_extract
            dataset
            demo
            docs
            environments
            model
            repair
            setttings
            tests
          requireScope: false
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
          wip: true

      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
